// Every text of the admin panel in one place. The admin panel is Serbian only.

export const adminText = {
  siteName: "Ćanti Apartmani",
  title: "Administracija",
  noApartments: "U bazi još nema nijednog apartmana.",
  nav: {
    label: "Administracija",
    brandLabel: "Admin",
    calendar: "Kalendar",
    settings: "Podešavanja",
    logout: "Odjava",
    loggingOut: "Odjavljivanje…",
  },
  login: {
    title: "Prijava",
    subtitle: "Administracija apartmana",
    email: "Mejl",
    password: "Lozinka",
    submit: "Prijavi se",
    submitting: "Prijavljivanje…",
    wrongCredentials: "Pogrešan mejl ili lozinka.",
    genericError: "Došlo je do greške, pokušajte ponovo.",
    forbidden: "Ovaj nalog nema pristup administraciji.",
  },
  api: {
    notLoggedIn: "Niste prijavljeni.",
    forbidden: "Nemate pristup.",
    apartmentNotFound: "Apartman ne postoji.",
    saveFailed: "Čuvanje nije uspelo, pokušajte ponovo.",
  },
  /** Shared by every admin form that saves something. */
  form: {
    saving: "Čuvanje…",
    saved: "Sačuvano ✓",
    priceInvalid: "Upišite cenu od 1 do 10.000 €.",
    networkError: "Čuvanje nije uspelo. Proverite internet i pokušajte ponovo.",
    sessionExpired: "Sesija je istekla.",
    loginAgain: "Prijavite se ponovo",
  },
  calendar: {
    title: "Kalendar cena",
    intro: "Dodirnite dan da promenite cenu. Za više dana dodirnite prvi, pa poslednji dan.",
    apartment: "Apartman",
    previousMonth: "Prethodni mesec",
    nextMonth: "Sledeći mesec",
    weekdays: ["Pon", "Uto", "Sre", "Čet", "Pet", "Sub", "Ned"],
    specialPrice: "posebna cena",
    pastDay: "prošao dan",
    today: "danas",
    legendSpecial: "posebna cena",
    legendSelected: "izabrano",
    legendPast: "prošli dani",
    basePrices: "Osnovne cene",
    weekday: "radni dan",
    friday: "petak",
    saturday: "subota",
    changeBasePrices: "Promeni osnovne cene",
    daysOne: "{n} dan",
    daysFew: "{n} dana",
    daysMany: "{n} dana",
  },
  editor: {
    title: "Izmena cene",
    pickHint: "Izaberite dan u kalendaru. Za više dana dodirnite prvi, pa poslednji dan.",
    extendHint: "Za više dana dodirnite i poslednji dan.",
    priceLabel: "Cena po noći",
    save: "Sačuvaj cenu",
    reset: "Vrati osnovnu cenu",
    cancel: "Otkaži",
    resetDone: "Vraćena osnovna cena ✓",
  },
  settings: {
    title: "Osnovne cene",
    intro: "Osnovna cena važi za svaku noć koja u kalendaru nema posebnu cenu.",
    weekday: "Radni dan",
    weekdayHint: "noći od nedelje do četvrtka",
    friday: "Petak",
    fridayHint: "noć sa petka na subotu",
    saturday: "Subota",
    saturdayHint: "noć sa subote na nedelju",
    save: "Sačuvaj osnovne cene",
    fromPrice: "Na sajtu piše: od {price} / noć",
  },
} as const;
