// Every text of the admin panel in one place. The admin panel is Serbian only.

export const adminText = {
  siteName: "Ćanti Apartmani",
  title: "Administracija",
  noApartments: "U bazi još nema nijednog apartmana.",
  nav: {
    label: "Administracija",
    brandLabel: "Admin",
    calendar: "Kalendar",
    reservations: "Rezervacije",
    /** Next to the badge, for screen readers: "Rezervacije, 2 na čekanju". */
    pendingCount: "{n} na čekanju",
    settings: "Podešavanja",
    logout: "Odjava",
    loggingOut: "Odjavljivanje…",
  },
  login: {
    title: "Prijava",
    subtitle: "Administracija apartmana",
    email: "Mejl",
    password: "Lozinka",
    submit: "Prijavi se",
    submitting: "Prijavljivanje…",
    wrongCredentials: "Pogrešan mejl ili lozinka.",
    genericError: "Došlo je do greške, pokušajte ponovo.",
    forbidden: "Ovaj nalog nema pristup administraciji.",
  },
  api: {
    notLoggedIn: "Niste prijavljeni.",
    forbidden: "Nemate pristup.",
    apartmentNotFound: "Apartman ne postoji.",
    reservationNotFound: "Rezervacija ne postoji.",
    saveFailed: "Čuvanje nije uspelo, pokušajte ponovo.",
  },
  /** Shared by every admin form that saves something. */
  form: {
    saving: "Čuvanje…",
    saved: "Sačuvano ✓",
    priceInvalid: "Upišite cenu od 1 do 10.000 €.",
    networkError: "Čuvanje nije uspelo. Proverite internet i pokušajte ponovo.",
    sessionExpired: "Sesija je istekla.",
    loginAgain: "Prijavite se ponovo",
  },
  calendar: {
    title: "Kalendar cena",
    intro: "Dodirnite dan da promenite cenu. Za više dana dodirnite prvi, pa poslednji dan.",
    apartment: "Apartman",
    previousMonth: "Prethodni mesec",
    nextMonth: "Sledeći mesec",
    weekdays: ["Pon", "Uto", "Sre", "Čet", "Pet", "Sub", "Ned"],
    specialPrice: "posebna cena",
    pastDay: "prošao dan",
    today: "danas",
    legendSpecial: "posebna cena",
    legendSelected: "izabrano",
    legendPast: "prošli dani",
    basePrices: "Osnovne cene",
    weekday: "radni dan",
    friday: "petak",
    saturday: "subota",
    changeBasePrices: "Promeni osnovne cene",
    daysOne: "{n} dan",
    daysFew: "{n} dana",
    daysMany: "{n} dana",
  },
  editor: {
    title: "Izmena cene",
    pickHint: "Izaberite dan u kalendaru. Za više dana dodirnite prvi, pa poslednji dan.",
    extendHint: "Za više dana dodirnite i poslednji dan.",
    priceLabel: "Cena po noći",
    save: "Sačuvaj cenu",
    reset: "Vrati osnovnu cenu",
    cancel: "Otkaži",
    resetDone: "Vraćena osnovna cena ✓",
  },
  settings: {
    title: "Osnovne cene",
    intro: "Osnovna cena važi za svaku noć koja u kalendaru nema posebnu cenu.",
    weekday: "Radni dan",
    weekdayHint: "noći od nedelje do četvrtka",
    friday: "Petak",
    fridayHint: "noć sa petka na subotu",
    saturday: "Subota",
    saturdayHint: "noć sa subote na nedelju",
    save: "Sačuvaj osnovne cene",
    fromPrice: "Na sajtu piše: od {price} / noć",
  },
  reservations: {
    title: "Rezervacije",
    intro: "Zahtevi sa sajta, ručne rezervacije i blokirani datumi. Predstojeće su prve.",
    filterLabel: "Prikaži rezervacije",
    filters: {
      pending: "Na čekanju",
      confirmed: "Potvrđene",
      blocked: "Blokade",
      cancelled: "Otkazane",
      all: "Sve",
    },
    status: {
      pending: "Čeka potvrdu",
      confirmed: "Potvrđena",
      blocked: "Blokirano",
      cancelled: "Otkazana",
    },
    upcoming: "Predstojeće",
    past: "Prošle",
    noUpcoming: "Nema predstojećih rezervacija u ovoj grupi.",
    showAll: "Prikaži sve rezervacije",
    pastLimit: "Prikazano je poslednjih {n} prošlih rezervacija.",
    blockedDates: "Datumi zatvoreni ručno, bez gosta.",
    noGuestName: "Gost bez imena",
    total: "Ukupno",
    source: {
      website: "Sa sajta",
      admin: "Uneto ručno",
    },
    received: "primljeno {date}",
    arrivesToday: "Dolazak danas",
    inProgress: "Gost je u apartmanu",
    leavesToday: "Odlazak danas",
    nightsOne: "{n} noć",
    nightsFew: "{n} noći",
    nightsMany: "{n} noći",
    guestsOne: "{n} gost",
    guestsFew: "{n} gosta",
    guestsMany: "{n} gostiju",
    actions: {
      label: "Akcije za rezervaciju",
      confirm: "Potvrdi",
      cancel: "Otkaži",
      confirming: "Potvrđivanje…",
      cancelling: "Otkazivanje…",
      cancelQuestion: "Otkazati ovu rezervaciju?",
      cancelHintEmail: "Datumi postaju slobodni, a gost dobija mejl.",
      cancelHintNoEmail: "Datumi postaju slobodni. Gost nema mejl, javite mu se telefonom.",
      cancelYes: "Da, otkaži",
      cancelNo: "Ne",
    },
    /** Shown after a change; "notified" = the guest got an email. */
    notices: {
      confirmedNotified: "Potvrđeno ✓ Gostu je poslat mejl.",
      confirmedNotNotified: "Potvrđeno ✓ Mejl gostu nije poslat, javite mu se telefonom.",
      cancelledNotified: "Otkazano ✓ Datumi su slobodni, gostu je poslat mejl.",
      cancelledNotNotified: "Otkazano ✓ Datumi su slobodni. Mejl gostu nije poslat, javite mu se telefonom.",
    },
    /** Why a status change is refused (PATCH /api/admin/reservations/[id] answers 409). */
    changeErrors: {
      alreadyConfirmed: "Ova rezervacija je već potvrđena.",
      alreadyCancelled: "Ova rezervacija je već otkazana.",
      blockCannotBeConfirmed: "Blokirani datumi se ne potvrđuju.",
      stayOver: "Boravak je već prošao, rezervacija se više ne menja.",
      changedMeanwhile: "Rezervacija je u međuvremenu promenjena. Osvežite stranicu.",
    },
  },
} as const;
